/**
 * Mapping of author names → personal page URLs.
 * Used by the AuthorList component to render linked names.
 */
const AUTHOR_LINKS = {
  "Audrey Cheng": "https://audreyccheng.com/",
  "Shu Liu": "https://shulynnliu.com/",
  "Melissa Pan": "https://melissa-pan.github.io/",
  "Ion Stoica": "https://people.eecs.berkeley.edu/~istoica/",
  "Bowen Wang": "https://github.com/abmfy",
  "Zhifei Li": "https://github.com/andylizf",
  "Tian Xia": "https://www.linkedin.com/in/tian-xia-5174192a0/",
  "Jeff Chen": "https://www.linkedin.com/in/jeff-chen-a9b7b4232/",
  "Charles Hong": "https://charleshong3.github.io/",
  "Jai Menon": "https://www.linkedin.com/in/jai-menon-725065109",
  "Rohan Kulkarni": "https://www.linkedin.com/in/rohandk",
  "Sesh Nalla": "https://www.linkedin.com/in/seshendranalla",
  "Mert Cemri": "https://people.eecs.berkeley.edu/~mert_cemri/",
  "Shubham Agarwal": "https://skejriwal44.github.io/",
  "Jiarong Xing": "https://jxing.me/",
  "Yifan Qiao": "https://yifanqiao.com/",
  "Jacopo Tagliabue": "https://jacopotagliabue.it/",
  "Aditya Desai": "https://apd10.github.io/",
  "Arin Kadakia": "https://www.linkedin.com/in/arinkadakia/",
  "SkyLight Team": "https://sky-light.eecs.berkeley.edu/#/about",
  "Shulu Li": "https://www.linkedin.com/in/shulu-li/",
  "Alvin Cheung": "https://people.eecs.berkeley.edu/~akcheung/",
  "Yakun Sophia Shao": "https://people.eecs.berkeley.edu/~ysshao/",
  "Sahil Bhatia": "https://x.com/sahilb17",
  "Temoor Tanveer": "https://ttanv.github.io/",
  "Lakshya A Agrawal": "https://lakshyaaagrawal.github.io/",
  "Shiyi Cao": "https://shiyicao.com/",
  "Alex Dimakis": "https://people.eecs.berkeley.edu/~alexdimakis/",
  "Koushik Sen": "https://people.eecs.berkeley.edu/~ksen",
  "Matei Zaharia": "https://people.eecs.berkeley.edu/~matei/",
  "Johannes Wehrstein": "https://www.informatik.tu-darmstadt.de/systems/systems_tuda/group/team_detail_120128.en.jsp",
  "Timo Eckmann": "https://www.informatik.tu-darmstadt.de/systems/systems_tuda/group/team_detail_147136.en.jsp",
  "Matthias Jasny": "https://www.informatik.tu-darmstadt.de/systems/systems_tuda/group/team_detail_111232.en.jsp",
  "Carsten Binnig": "https://www.informatik.tu-darmstadt.de/systems/systems_tuda/group/team_detail_18624.en.jsp",
  "Yuhao Zhang": "https://yhzhang.info/",
  "Eric Liang": "https://scholar.google.com/citations?user=wmZTE5gAAAAJ&hl=en",
  "Ryan Marcus": "https://rmarcus.info/",
  "ADRS Team": "https://ucbskyadrs.github.io/about/",
  "Yahya Emara": "https://yahya010.github.io/",
  "Ali Tehrani": "https://tehrani.xyz/",
  "Mohamed Abdelfattah": "https://www.mohsaied.com/",
  "Lesley(Yajie) Zhou": "https://lesleychou.github.io/",
  "Ao Li": "https://aoli.al/",
  "Zaoxing Liu": "https://zaoxing.github.io/",
  "Vyas Sekar": "https://users.ece.cmu.edu/~vsekar/",
};

export default AUTHOR_LINKS;
